language: java
jdk:
  - oraclejdk7

install:
  - mvn -DskipTests=true install
  - pip install http://jandy.io/jandy-runner.egg
script:
  - mvn clean package
  - jandy java -jar target/jasypt-test-1.0-SNAPSHOT.jar Password123 "I am opensource developer"