language: java
jdk:
  - oraclejdk7

install:
  - mvn -DskipTests=true install
  - sudo pip install http://jandy.io/jandy-python.zip
script:
  - mvn clean package
  - jandy java -jar target/jasypt-test-1.0-SNAPSHOT.jar PasswordPasswordPassword123 "I am opensource developer or I am opensource developer or I am opensource developer"